'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.ICalculator")>  _
    Public Interface ICalculator
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Add", ReplyAction:="http://tempuri.org/ICalculator/AddResponse")>  _
        Function Add(ByVal number1 As Integer, ByVal number2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Subtract", ReplyAction:="http://tempuri.org/ICalculator/SubtractResponse")>  _
        Function Subtract(ByVal number1 As Integer, ByVal number2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Multiply", ReplyAction:="http://tempuri.org/ICalculator/MultiplyResponse")>  _
        Function Multiply(ByVal number1 As Integer, ByVal number2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Divide", ReplyAction:="http://tempuri.org/ICalculator/DivideResponse")>  _
        Function Divide(ByVal number1 As Integer, ByVal number2 As Integer) As Integer
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICalculatorChannel
        Inherits ServiceReference1.ICalculator, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CalculatorClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ICalculator)
        Implements ServiceReference1.ICalculator
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Add(ByVal number1 As Integer, ByVal number2 As Integer) As Integer Implements ServiceReference1.ICalculator.Add
            Return MyBase.Channel.Add(number1, number2)
        End Function
        
        Public Function Subtract(ByVal number1 As Integer, ByVal number2 As Integer) As Integer Implements ServiceReference1.ICalculator.Subtract
            Return MyBase.Channel.Subtract(number1, number2)
        End Function
        
        Public Function Multiply(ByVal number1 As Integer, ByVal number2 As Integer) As Integer Implements ServiceReference1.ICalculator.Multiply
            Return MyBase.Channel.Multiply(number1, number2)
        End Function
        
        Public Function Divide(ByVal number1 As Integer, ByVal number2 As Integer) As Integer Implements ServiceReference1.ICalculator.Divide
            Return MyBase.Channel.Divide(number1, number2)
        End Function
    End Class
End Namespace
