'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Employee
    Public Property EmployeeID As Integer
    Public Property LastName As String
    Public Property FirstName As String
    Public Property Title As String
    Public Property TitleOfCourtesy As String
    Public Property BirthDate As Nullable(Of Date)
    Public Property HireDate As Nullable(Of Date)
    Public Property Address As String
    Public Property City As String
    Public Property Region As String
    Public Property PostalCode As String
    Public Property Country As String
    Public Property HomePhone As String
    Public Property Extension As String
    Public Property Photo As Byte()
    Public Property Notes As String
    Public Property ReportsTo As Nullable(Of Integer)
    Public Property PhotoPath As String

    Public Overridable Property Employees1 As ICollection(Of Employee) = New HashSet(Of Employee)
    Public Overridable Property Employee1 As Employee
    Public Overridable Property Orders As ICollection(Of Order) = New HashSet(Of Order)

End Class
