'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class NorthwindEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=NorthwindEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
	    Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Categories() As DbSet(Of Category)
    Public Property Customers() As DbSet(Of Customer)
    Public Property Employees() As DbSet(Of Employee)
    Public Property Order_Details() As DbSet(Of Order_Detail)
    Public Property Orders() As DbSet(Of Order)
    Public Property Products() As DbSet(Of Product)

End Class
