'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceProxies
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MathRequest", [Namespace]:="http://schemas.datacontract.org/2004/07/HSBCServicesApp.Contracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MathRequest
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Number1Field As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Number2Field As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperationField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Number1() As Integer
            Get
                Return Me.Number1Field
            End Get
            Set
                If (Me.Number1Field.Equals(value) <> true) Then
                    Me.Number1Field = value
                    Me.RaisePropertyChanged("Number1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Number2() As Integer
            Get
                Return Me.Number2Field
            End Get
            Set
                If (Me.Number2Field.Equals(value) <> true) Then
                    Me.Number2Field = value
                    Me.RaisePropertyChanged("Number2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Operation() As String
            Get
                Return Me.OperationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperationField, value) <> true) Then
                    Me.OperationField = value
                    Me.RaisePropertyChanged("Operation")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="MathResult", [Namespace]:="http://schemas.datacontract.org/2004/07/HSBCServicesApp.Contracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class MathResult
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Number1Field As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Number2Field As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperationField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ResultField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Number1() As Integer
            Get
                Return Me.Number1Field
            End Get
            Set
                If (Me.Number1Field.Equals(value) <> true) Then
                    Me.Number1Field = value
                    Me.RaisePropertyChanged("Number1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Number2() As Integer
            Get
                Return Me.Number2Field
            End Get
            Set
                If (Me.Number2Field.Equals(value) <> true) Then
                    Me.Number2Field = value
                    Me.RaisePropertyChanged("Number2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Operation() As String
            Get
                Return Me.OperationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperationField, value) <> true) Then
                    Me.OperationField = value
                    Me.RaisePropertyChanged("Operation")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Result() As Integer
            Get
                Return Me.ResultField
            End Get
            Set
                If (Me.ResultField.Equals(value) <> true) Then
                    Me.ResultField = value
                    Me.RaisePropertyChanged("Result")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="OperationFailureDetail", [Namespace]:="http://schemas.datacontract.org/2004/07/HSBCServicesApp.Contracts"),  _
     System.SerializableAttribute()>  _
    Partial Public Class OperationFailureDetail
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ErrorMessageField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Number1Field As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Number2Field As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperationField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ErrorMessage() As String
            Get
                Return Me.ErrorMessageField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ErrorMessageField, value) <> true) Then
                    Me.ErrorMessageField = value
                    Me.RaisePropertyChanged("ErrorMessage")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Number1() As Integer
            Get
                Return Me.Number1Field
            End Get
            Set
                If (Me.Number1Field.Equals(value) <> true) Then
                    Me.Number1Field = value
                    Me.RaisePropertyChanged("Number1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Number2() As Integer
            Get
                Return Me.Number2Field
            End Get
            Set
                If (Me.Number2Field.Equals(value) <> true) Then
                    Me.Number2Field = value
                    Me.RaisePropertyChanged("Number2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Operation() As String
            Get
                Return Me.OperationField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OperationField, value) <> true) Then
                    Me.OperationField = value
                    Me.RaisePropertyChanged("Operation")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceProxies.ICalculator")>  _
    Public Interface ICalculator
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Add", ReplyAction:="http://tempuri.org/ICalculator/AddResponse")>  _
        Function Add(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Subtract", ReplyAction:="http://tempuri.org/ICalculator/SubtractResponse")>  _
        Function Subtract(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Multiply", ReplyAction:="http://tempuri.org/ICalculator/MultiplyResponse")>  _
        Function Multiply(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Divide", ReplyAction:="http://tempuri.org/ICalculator/DivideResponse")>  _
        Function Divide(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICalculatorChannel
        Inherits ServiceProxies.ICalculator, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CalculatorClient
        Inherits System.ServiceModel.ClientBase(Of ServiceProxies.ICalculator)
        Implements ServiceProxies.ICalculator
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Add(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer Implements ServiceProxies.ICalculator.Add
            Return MyBase.Channel.Add(Number1, Number2)
        End Function
        
        Public Function Subtract(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer Implements ServiceProxies.ICalculator.Subtract
            Return MyBase.Channel.Subtract(Number1, Number2)
        End Function
        
        Public Function Multiply(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer Implements ServiceProxies.ICalculator.Multiply
            Return MyBase.Channel.Multiply(Number1, Number2)
        End Function
        
        Public Function Divide(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer Implements ServiceProxies.ICalculator.Divide
            Return MyBase.Channel.Divide(Number1, Number2)
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceProxies.IAdvCalculator")>  _
    Public Interface IAdvCalculator
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAdvCalculator/Process", ReplyAction:="http://tempuri.org/IAdvCalculator/ProcessResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceProxies.OperationFailureDetail), Action:="http://tempuri.org/IAdvCalculator/ProcessOperationFailureDetailFault", Name:="OperationFailureDetail", [Namespace]:="http://schemas.datacontract.org/2004/07/HSBCServicesApp.Contracts")>  _
        Function Process(ByVal request As ServiceProxies.MathRequest) As ServiceProxies.MathResult
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAdvCalculator/ProcessAll", ReplyAction:="http://tempuri.org/IAdvCalculator/ProcessAllResponse"),  _
         System.ServiceModel.FaultContractAttribute(GetType(ServiceProxies.OperationFailureDetail), Action:="http://tempuri.org/IAdvCalculator/ProcessAllOperationFailureDetailFault", Name:="OperationFailureDetail", [Namespace]:="http://schemas.datacontract.org/2004/07/HSBCServicesApp.Contracts")>  _
        Function ProcessAll(ByVal request As ServiceProxies.MathRequest) As System.Collections.Generic.List(Of ServiceProxies.MathResult)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAdvCalculatorChannel
        Inherits ServiceProxies.IAdvCalculator, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AdvCalculatorClient
        Inherits System.ServiceModel.ClientBase(Of ServiceProxies.IAdvCalculator)
        Implements ServiceProxies.IAdvCalculator
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Process(ByVal request As ServiceProxies.MathRequest) As ServiceProxies.MathResult Implements ServiceProxies.IAdvCalculator.Process
            Return MyBase.Channel.Process(request)
        End Function
        
        Public Function ProcessAll(ByVal request As ServiceProxies.MathRequest) As System.Collections.Generic.List(Of ServiceProxies.MathResult) Implements ServiceProxies.IAdvCalculator.ProcessAll
            Return MyBase.Channel.ProcessAll(request)
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceProxies.IAdvOneWayCalculator")>  _
    Public Interface IAdvOneWayCalculator
        
        <System.ServiceModel.OperationContractAttribute(IsOneWay:=true, Action:="http://tempuri.org/IAdvOneWayCalculator/ProcessOneWay")>  _
        Sub ProcessOneWay(ByVal request As ServiceProxies.MathRequest)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAdvOneWayCalculatorChannel
        Inherits ServiceProxies.IAdvOneWayCalculator, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AdvOneWayCalculatorClient
        Inherits System.ServiceModel.ClientBase(Of ServiceProxies.IAdvOneWayCalculator)
        Implements ServiceProxies.IAdvOneWayCalculator
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub ProcessOneWay(ByVal request As ServiceProxies.MathRequest) Implements ServiceProxies.IAdvOneWayCalculator.ProcessOneWay
            MyBase.Channel.ProcessOneWay(request)
        End Sub
    End Class
End Namespace
