'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceProxies
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceProxies.IChatService", CallbackContract:=GetType(ServiceProxies.IChatServiceCallback))>  _
    Public Interface IChatService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChatService/Login", ReplyAction:="http://tempuri.org/IChatService/LoginResponse")>  _
        Sub Login(ByVal Name As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChatService/PostMessage", ReplyAction:="http://tempuri.org/IChatService/PostMessageResponse")>  _
        Sub PostMessage(ByVal Message As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChatService/LogOff", ReplyAction:="http://tempuri.org/IChatService/LogOffResponse")>  _
        Sub LogOff()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IChatServiceCallback
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IChatService/ReceiveMessage", ReplyAction:="http://tempuri.org/IChatService/ReceiveMessageResponse")>  _
        Sub ReceiveMessage(ByVal Message As String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IChatServiceChannel
        Inherits ServiceProxies.IChatService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ChatServiceClient
        Inherits System.ServiceModel.DuplexClientBase(Of ServiceProxies.IChatService)
        Implements ServiceProxies.IChatService
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext)
            MyBase.New(callbackInstance)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String)
            MyBase.New(callbackInstance, endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal callbackInstance As System.ServiceModel.InstanceContext, ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(callbackInstance, binding, remoteAddress)
        End Sub
        
        Public Sub Login(ByVal Name As String) Implements ServiceProxies.IChatService.Login
            MyBase.Channel.Login(Name)
        End Sub
        
        Public Sub PostMessage(ByVal Message As String) Implements ServiceProxies.IChatService.PostMessage
            MyBase.Channel.PostMessage(Message)
        End Sub
        
        Public Sub LogOff() Implements ServiceProxies.IChatService.LogOff
            MyBase.Channel.LogOff
        End Sub
    End Class
End Namespace
