'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceProxies
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceProxies.ICalculator")>  _
    Public Interface ICalculator
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Add", ReplyAction:="http://tempuri.org/ICalculator/AddResponse")>  _
        Function Add(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ICalculator/Add", ReplyAction:="http://tempuri.org/ICalculator/AddResponse")>  _
        Function BeginAdd(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndAdd(ByVal result As System.IAsyncResult) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Subtract", ReplyAction:="http://tempuri.org/ICalculator/SubtractResponse")>  _
        Function Subtract(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ICalculator/Subtract", ReplyAction:="http://tempuri.org/ICalculator/SubtractResponse")>  _
        Function BeginSubtract(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndSubtract(ByVal result As System.IAsyncResult) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Multiply", ReplyAction:="http://tempuri.org/ICalculator/MultiplyResponse")>  _
        Function Multiply(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ICalculator/Multiply", ReplyAction:="http://tempuri.org/ICalculator/MultiplyResponse")>  _
        Function BeginMultiply(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndMultiply(ByVal result As System.IAsyncResult) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICalculator/Divide", ReplyAction:="http://tempuri.org/ICalculator/DivideResponse")>  _
        Function Divide(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(AsyncPattern:=true, Action:="http://tempuri.org/ICalculator/Divide", ReplyAction:="http://tempuri.org/ICalculator/DivideResponse")>  _
        Function BeginDivide(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        
        Function EndDivide(ByVal result As System.IAsyncResult) As Integer
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICalculatorChannel
        Inherits ServiceProxies.ICalculator, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AddCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Integer
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class SubtractCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Integer
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MultiplyCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Integer
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DivideCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Public Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        Public ReadOnly Property Result() As Integer
            Get
                MyBase.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Integer)
            End Get
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CalculatorClient
        Inherits System.ServiceModel.ClientBase(Of ServiceProxies.ICalculator)
        Implements ServiceProxies.ICalculator
        
        Private onBeginAddDelegate As BeginOperationDelegate
        
        Private onEndAddDelegate As EndOperationDelegate
        
        Private onAddCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginSubtractDelegate As BeginOperationDelegate
        
        Private onEndSubtractDelegate As EndOperationDelegate
        
        Private onSubtractCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginMultiplyDelegate As BeginOperationDelegate
        
        Private onEndMultiplyDelegate As EndOperationDelegate
        
        Private onMultiplyCompletedDelegate As System.Threading.SendOrPostCallback
        
        Private onBeginDivideDelegate As BeginOperationDelegate
        
        Private onEndDivideDelegate As EndOperationDelegate
        
        Private onDivideCompletedDelegate As System.Threading.SendOrPostCallback
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Event AddCompleted As System.EventHandler(Of AddCompletedEventArgs)
        
        Public Event SubtractCompleted As System.EventHandler(Of SubtractCompletedEventArgs)
        
        Public Event MultiplyCompleted As System.EventHandler(Of MultiplyCompletedEventArgs)
        
        Public Event DivideCompleted As System.EventHandler(Of DivideCompletedEventArgs)
        
        Public Function Add(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer Implements ServiceProxies.ICalculator.Add
            Return MyBase.Channel.Add(Number1, Number2)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginAdd(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ServiceProxies.ICalculator.BeginAdd
            Return MyBase.Channel.BeginAdd(Number1, Number2, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndAdd(ByVal result As System.IAsyncResult) As Integer Implements ServiceProxies.ICalculator.EndAdd
            Return MyBase.Channel.EndAdd(result)
        End Function
        
        Private Function OnBeginAdd(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim Number1 As Integer = CType(inValues(0),Integer)
            Dim Number2 As Integer = CType(inValues(1),Integer)
            Return Me.BeginAdd(Number1, Number2, callback, asyncState)
        End Function
        
        Private Function OnEndAdd(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Integer = Me.EndAdd(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnAddCompleted(ByVal state As Object)
            If (Not (Me.AddCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent AddCompleted(Me, New AddCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub AddAsync(ByVal Number1 As Integer, ByVal Number2 As Integer)
            Me.AddAsync(Number1, Number2, Nothing)
        End Sub
        
        Public Overloads Sub AddAsync(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal userState As Object)
            If (Me.onBeginAddDelegate Is Nothing) Then
                Me.onBeginAddDelegate = AddressOf Me.OnBeginAdd
            End If
            If (Me.onEndAddDelegate Is Nothing) Then
                Me.onEndAddDelegate = AddressOf Me.OnEndAdd
            End If
            If (Me.onAddCompletedDelegate Is Nothing) Then
                Me.onAddCompletedDelegate = AddressOf Me.OnAddCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginAddDelegate, New Object() {Number1, Number2}, Me.onEndAddDelegate, Me.onAddCompletedDelegate, userState)
        End Sub
        
        Public Function Subtract(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer Implements ServiceProxies.ICalculator.Subtract
            Return MyBase.Channel.Subtract(Number1, Number2)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginSubtract(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ServiceProxies.ICalculator.BeginSubtract
            Return MyBase.Channel.BeginSubtract(Number1, Number2, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndSubtract(ByVal result As System.IAsyncResult) As Integer Implements ServiceProxies.ICalculator.EndSubtract
            Return MyBase.Channel.EndSubtract(result)
        End Function
        
        Private Function OnBeginSubtract(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim Number1 As Integer = CType(inValues(0),Integer)
            Dim Number2 As Integer = CType(inValues(1),Integer)
            Return Me.BeginSubtract(Number1, Number2, callback, asyncState)
        End Function
        
        Private Function OnEndSubtract(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Integer = Me.EndSubtract(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnSubtractCompleted(ByVal state As Object)
            If (Not (Me.SubtractCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent SubtractCompleted(Me, New SubtractCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub SubtractAsync(ByVal Number1 As Integer, ByVal Number2 As Integer)
            Me.SubtractAsync(Number1, Number2, Nothing)
        End Sub
        
        Public Overloads Sub SubtractAsync(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal userState As Object)
            If (Me.onBeginSubtractDelegate Is Nothing) Then
                Me.onBeginSubtractDelegate = AddressOf Me.OnBeginSubtract
            End If
            If (Me.onEndSubtractDelegate Is Nothing) Then
                Me.onEndSubtractDelegate = AddressOf Me.OnEndSubtract
            End If
            If (Me.onSubtractCompletedDelegate Is Nothing) Then
                Me.onSubtractCompletedDelegate = AddressOf Me.OnSubtractCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginSubtractDelegate, New Object() {Number1, Number2}, Me.onEndSubtractDelegate, Me.onSubtractCompletedDelegate, userState)
        End Sub
        
        Public Function Multiply(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer Implements ServiceProxies.ICalculator.Multiply
            Return MyBase.Channel.Multiply(Number1, Number2)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginMultiply(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ServiceProxies.ICalculator.BeginMultiply
            Return MyBase.Channel.BeginMultiply(Number1, Number2, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndMultiply(ByVal result As System.IAsyncResult) As Integer Implements ServiceProxies.ICalculator.EndMultiply
            Return MyBase.Channel.EndMultiply(result)
        End Function
        
        Private Function OnBeginMultiply(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim Number1 As Integer = CType(inValues(0),Integer)
            Dim Number2 As Integer = CType(inValues(1),Integer)
            Return Me.BeginMultiply(Number1, Number2, callback, asyncState)
        End Function
        
        Private Function OnEndMultiply(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Integer = Me.EndMultiply(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnMultiplyCompleted(ByVal state As Object)
            If (Not (Me.MultiplyCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent MultiplyCompleted(Me, New MultiplyCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub MultiplyAsync(ByVal Number1 As Integer, ByVal Number2 As Integer)
            Me.MultiplyAsync(Number1, Number2, Nothing)
        End Sub
        
        Public Overloads Sub MultiplyAsync(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal userState As Object)
            If (Me.onBeginMultiplyDelegate Is Nothing) Then
                Me.onBeginMultiplyDelegate = AddressOf Me.OnBeginMultiply
            End If
            If (Me.onEndMultiplyDelegate Is Nothing) Then
                Me.onEndMultiplyDelegate = AddressOf Me.OnEndMultiply
            End If
            If (Me.onMultiplyCompletedDelegate Is Nothing) Then
                Me.onMultiplyCompletedDelegate = AddressOf Me.OnMultiplyCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginMultiplyDelegate, New Object() {Number1, Number2}, Me.onEndMultiplyDelegate, Me.onMultiplyCompletedDelegate, userState)
        End Sub
        
        Public Function Divide(ByVal Number1 As Integer, ByVal Number2 As Integer) As Integer Implements ServiceProxies.ICalculator.Divide
            Return MyBase.Channel.Divide(Number1, Number2)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function BeginDivide(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements ServiceProxies.ICalculator.BeginDivide
            Return MyBase.Channel.BeginDivide(Number1, Number2, callback, asyncState)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Function EndDivide(ByVal result As System.IAsyncResult) As Integer Implements ServiceProxies.ICalculator.EndDivide
            Return MyBase.Channel.EndDivide(result)
        End Function
        
        Private Function OnBeginDivide(ByVal inValues() As Object, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Dim Number1 As Integer = CType(inValues(0),Integer)
            Dim Number2 As Integer = CType(inValues(1),Integer)
            Return Me.BeginDivide(Number1, Number2, callback, asyncState)
        End Function
        
        Private Function OnEndDivide(ByVal result As System.IAsyncResult) As Object()
            Dim retVal As Integer = Me.EndDivide(result)
            Return New Object() {retVal}
        End Function
        
        Private Sub OnDivideCompleted(ByVal state As Object)
            If (Not (Me.DivideCompletedEvent) Is Nothing) Then
                Dim e As InvokeAsyncCompletedEventArgs = CType(state,InvokeAsyncCompletedEventArgs)
                RaiseEvent DivideCompleted(Me, New DivideCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState))
            End If
        End Sub
        
        Public Overloads Sub DivideAsync(ByVal Number1 As Integer, ByVal Number2 As Integer)
            Me.DivideAsync(Number1, Number2, Nothing)
        End Sub
        
        Public Overloads Sub DivideAsync(ByVal Number1 As Integer, ByVal Number2 As Integer, ByVal userState As Object)
            If (Me.onBeginDivideDelegate Is Nothing) Then
                Me.onBeginDivideDelegate = AddressOf Me.OnBeginDivide
            End If
            If (Me.onEndDivideDelegate Is Nothing) Then
                Me.onEndDivideDelegate = AddressOf Me.OnEndDivide
            End If
            If (Me.onDivideCompletedDelegate Is Nothing) Then
                Me.onDivideCompletedDelegate = AddressOf Me.OnDivideCompleted
            End If
            MyBase.InvokeAsync(Me.onBeginDivideDelegate, New Object() {Number1, Number2}, Me.onEndDivideDelegate, Me.onDivideCompletedDelegate, userState)
        End Sub
    End Class
End Namespace
